### ISSUE TITLE
JobGuardian should shutdown so TRIGGER ONCE works as expected

### ISSUE THREAD

**Issue by cbcwebdev** [vertica/PSTL#3]
Currently, JobGuardian remains online if underlying JobDaemons and QueryDaemons die off intentionally (e.g., they are done). In a TRIGGER ONCE workload, a QueryDaemon stops after processing a micro-batch. If that was the only query in a job, JobDaemon stops after QueryDaemon stops. JobGuardian stops in response to this (if there was only one job launched in this JVM), but the JVM remains online.

From JobGuardian:
```
private def maybeShutdownCleanly(): Unit = {
  if(context.children.isEmpty) {
    context.stop(self)
  }
}
```

Should be:
```
private def maybeShutdownCleanly(): Unit = {
  if(context.children.isEmpty) {
    CoordinatedShutdown(context.system).run()
  }
}
```

**Comment by vnnv01** [comment]
Code is updated in recent commit 3e1518c18aa72bacfa95fd5dc3fd2dba4a3705d6. Closing this issue
